version: "3"

services:

  Manager:
    image: mdaastec/manager:1.0
    ports: 
      - "${ManagerRequestPort}:${ManagerRequestPort}"
      - "${ManagerPublishingPort}:${ManagerPublishingPort}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "manager_config:/app/Config/"
      #- "./Config/Model.json:/app/Config/Model.json"
    environment:
      RegistrationResponderPort: ${ManagerRequestPort}
      MessagePublisherPort: ${ManagerPublishingPort}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

#  MqttBroker:
#    image: eclipse-mosquitto
#    hostname: MqttBroker
#    ports:
#      - "1883:1883"
#      - "9001:9001"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"

volumes:
  manager_config: